---
abstract: 'Simply make your app pluggable'
author:
  - 'Maurice Mengel <mauricemengel@gmail.com>'
build_requires:
  Data::Dumper: 0
  File::Spec: 0
  FindBin: 0
  Scalar::Util: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plugin-Simple
requires:
  Carp: 0
  Class::Load: 0
  Moose: 0
  Moose::Role: 0
  namespace::autoclean: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Plugin-Simple
  homepage: https://github.com/mokko/p5-plugin-simple/wiki
  repository: git://github.com/mokko/p5-plugin-simple.git
version: 0.001
